name: CI Tests
on:
  pull_request:
    branches:
      - 'develop'
env:
  AWS_DEFAULT_REGION: 'eu-central-1'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}  # Needed to run conda
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: KengoTODA/actions-setup-docker-compose@v1
      - name: Install Docker-Compose
        with:
          version: '2.5.0'

      - uses: conda-incubator/setup-miniconda@v2
      - name: Set up Conda and activate environment
        with:
          activate-environment: mlops-zoomcamp
          environment-file: mlops-zoomcamp-env.yaml
          auto-activate-base: false

      - name: Run Unit tests
        run: pytest tests/

      - name: Lint
        run: pylint --recursive=y .

      - name: Integration Test
        working-directory: "integration-tests"
        run: |
          bash ./run.sh
